title: Arya's Page
description: Arya Zadebrahimi. Sharif University of Technology. Bioinformatics. Computer Science. Systems Biology. آریا زادابراهیمی.
permalink: ':title/'
# domain: my-site.github.io
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Arya Zadebrahimi # add your name
author-img: arya-zadebrahimi.jpg # add your photo
about-author: M.Sc. in Bioinformatics, Experience across multiple areas of computer science, Eager to research and solve challenging problems. # add description
social-telegram: arya_zero # add your Facebook handle
social-github: aryazady # add your Github handle
social-linkedin: arya-z # add your Linkedin handle
social-email: aryazadebrahimi@gmail.com # add your Email address
# theme_skin: blue # blue turquoise green berry orange ceramic teal oceanstale

# Disqus
# discus-identifier: arya-z # add your discus identifier

# # Tracker
# analytics: # Google Analytics

# Sass/SCSS
# sass:
#   sass_dir: /assets/css
#   style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

encoding: "utf-8"

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  # - jekyll-paginate
  - jemoji

# paginate: 8
# paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
